# -*- coding: utf-8 -*-
"""UNet3d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qVm6fEnTq4J9Cyf5SdZoVwjMEX7HuPrR
"""

!pip install monai torch

#added by CL to make imports work
from google.colab import drive
drive.mount('/content/drive')

# verify your folder is visible
import os
#!ls '/content/drive/MyDrive/'

# copy it into Colab's working directory
!cp -r '/content/drive/MyDrive/277B_FinalProject' /content/

# navigate into it
os.chdir('/content/277B_FinalProject/Trans-U-Net')
!ls

from monai.apps import DecathlonDataset

from monai.losses import DiceLoss
from monai.metrics import DiceMetric

from monai.transforms import (
    Activations,
    Activationsd,
    AsDiscrete,
    AsDiscreted,
    Compose,
    Invertd,
    LoadImaged,
    MapTransform,
    NormalizeIntensityd,
    Orientationd,
    RandFlipd,
    RandScaleIntensityd,
    RandShiftIntensityd,
    RandSpatialCropd,
    Resize,
    Spacingd,
    EnsureTyped,
    EnsureChannelFirstd,
)
import time
from monai.data import DataLoader, decollate_batch
from monai.inferers import sliding_window_inference

import torch
import torch.nn as nn
import torch.nn.functional as F

import math
import numpy as np

import interp_methods
from resize_right import resize

"""@misc{ResizeRight,
  author = {Shocher, Assaf},
  title = {ResizeRight},
  year = {2018},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/assafshocher/ResizeRight}},
}
"""

class Downsample():
    """Class made for downsampling 5D tensors from 3D image data to be able to run on local computers"""
    def __init__(self, img_data, max_hwd = (64, 64, 64), is_numpy = False):
        if is_numpy:
            b, c, h, w, d = img_data.shape
        else:
            b, c, h, w, d = img_data.size()
        assert (h, w, d) > max_hwd, "Are you sure you want to downsample? Check the dimensions again!"
        self.scale_factors = (1, 1, max_hwd[0]/h, max_hwd[1]/w, max_hwd[2]/d) # leave b and c unchanged

    def __call__(self, x: torch.Tensor):
        new_x = resize(x, scale_factors=self.scale_factors, out_shape=None,
                    interp_method=interp_methods.lanczos2, support_sz=None,
                    antialiasing=True, by_convs=False, scale_tolerance=0.1,
                    max_numerator=10, pad_mode='constant')
        return new_x

class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv3d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm3d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv3d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm3d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.conv(x)


class UNet3D(nn.Module):
    def __init__(self, in_channels=1, out_channels=1):
        super().__init__()
        self.encoder1 = DoubleConv(in_channels, 64)
        self.pool1 = nn.MaxPool3d(kernel_size=2, stride=2)
        self.encoder2 = DoubleConv(64, 128)
        self.pool2 = nn.MaxPool3d(kernel_size=2, stride=2)
        self.encoder3 = DoubleConv(128, 256)
        self.pool3 = nn.MaxPool3d(kernel_size=2, stride=2)

        self.bottleneck = DoubleConv(256, 512)

        self.upconv3 = nn.ConvTranspose3d(512, 256, kernel_size=2, stride=2)
        self.decoder3 = DoubleConv(512, 256)
        self.upconv2 = nn.ConvTranspose3d(256, 128, kernel_size=2, stride=2)
        self.decoder2 = DoubleConv(256, 128)
        self.upconv1 = nn.ConvTranspose3d(128, 64, kernel_size=2, stride=2)
        self.decoder1 = DoubleConv(128, 64)

        self.out_conv = nn.Conv3d(64, out_channels, kernel_size=1)

    def forward(self, x):
        #print("initial x input shape", x.size())
        enc1 = self.encoder1(x)
        enc2 = self.encoder2(self.pool1(enc1))
        enc3 = self.encoder3(self.pool2(enc2))

        bottleneck = self.bottleneck(self.pool3(enc3))

        dec3 = self.upconv3(bottleneck)
        dec3 = torch.cat((dec3, enc3), dim=1)
        dec3 = self.decoder3(dec3)
        dec2 = self.upconv2(dec3)
        dec2 = torch.cat((dec2, enc2), dim=1)
        dec2 = self.decoder2(dec2)
        dec1 = self.upconv1(dec2)
        dec1 = torch.cat((dec1, enc1), dim=1)
        dec1 = self.decoder1(dec1)

        out = self.out_conv(dec1)
        #print("out shape", out.size())
        return out

#class Classifier(nn.Module)

from torch.utils.data import Dataset, DataLoader
import numpy as np

class VolumetricDataset(Dataset):
    def __init__(self, volumes, masks):
        self.volumes = volumes
        self.masks = masks

    def __len__(self):
        return len(self.volumes)

    def __getitem__(self, idx):
        volume = self.volumes[idx]
        mask = self.masks[idx]
        volume = torch.from_numpy(volume).float().unsqueeze(0)
        mask = torch.from_numpy(mask).float().unsqueeze(0)
        return volume, mask


# Example usage
'''
volumes = np.random.rand(10, 64, 64, 64)
masks = np.random.randint(0, 2, size=(10, 64, 64, 64))
dataset = VolumetricDataset(volumes, masks)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)'''

from monai.apps import DecathlonDataset
from monai.losses import DiceLoss
from monai.metrics import DiceMetric

from monai.transforms import (
    Activations,
    Activationsd,
    AsDiscrete,
    AsDiscreted,
    Compose,
    Invertd,
    LoadImaged,
    MapTransform,
    NormalizeIntensityd,
    Orientationd,
    RandFlipd,
    RandScaleIntensityd,
    RandShiftIntensityd,
    RandSpatialCropd,
    Spacingd,
    EnsureTyped,
    EnsureChannelFirstd,
)

# import os
# # os.environ['MONAI_DATA_DIRECTORY'] = 'monai_data'
# # directory = os.environ.get("MONAI_DATA_DIRECTORY")
# if directory is not None:
#     os.makedirs(directory, exist_ok=True)
# root_dir = tempfile.mkdtemp() if directory is None else directory
# print(root_dir)

#Creates monai data folder that persists across reuntime disconnects
import os
# os.environ['MONAI_DATA_DIRECTORY'] = 'monai_data'
directory = '/content/drive/MyDrive/277B_FinalProject/Trans-U-Net/monai_data'
root_dir = directory
print(root_dir)

# # os.environ['MONAI_DATA_DIRECTORY'] = 'monai_data'
# # directory = os.environ.get("MONAI_DATA_DIRECTORY")
# if directory is not None:
#     os.makedirs(directory, exist_ok=True)
# root_dir = tempfile.mkdtemp() if directory is None else directory
# print(root_dir)

class ConvertToMultiChannelBasedOnBratsClasses(MapTransform):
    """
    Convert labels to multi channels based on brats classes:
    label 1 is the peritumoral edema
    label 2 is the GD-enhancing tumor
    label 3 is the necrotic and non-enhancing tumor core
    The possible classes are TC (Tumor core), WT (Whole tumor)
    and ET (Enhancing tumor).

    """

    def __call__(self, data):
        d = dict(data)
        for key in self.keys:
            result = []
            # merge label 2 and label 3 to construct TC
            result.append(torch.logical_or(d[key] == 2, d[key] == 3))
            # merge labels 1, 2 and 3 to construct WT
            result.append(torch.logical_or(torch.logical_or(d[key] == 2, d[key] == 3), d[key] == 1))
            # label 2 is ET
            result.append(d[key] == 2)
            d[key] = torch.stack(result, axis=0).float()
        return d

class SingleModality(MapTransform):
  #here keys = 'images'
    def __call__(self, data):
        d = dict(data)
        for image in self.keys:
          d[image] = d[image][0:1,:,:,:]
        return d

train_transform = Compose(
    [
        # load 4 Nifti images and stack them together
        LoadImaged(keys=["image", "label"]),
        EnsureChannelFirstd(keys="image"),
        SingleModality(keys="image"),
        EnsureTyped(keys=["image", "label"]),
        ConvertToMultiChannelBasedOnBratsClasses(keys="label"),
        Orientationd(keys=["image", "label"], axcodes="RAS"),
        Spacingd(
            keys=["image", "label"],
            pixdim=(1.0, 1.0, 1.0),
            mode=("bilinear", "nearest"),
        ),
        RandSpatialCropd(keys=["image", "label"], roi_size=[224, 224, 144], random_size=False), # Reverted ROI size
        RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=0),
        RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=1),
        RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=2),
        NormalizeIntensityd(keys="image", nonzero=True, channel_wise=True),
        RandScaleIntensityd(keys="image", factors=0.1, prob=1.0),
        RandShiftIntensityd(keys="image", offsets=0.1, prob=1.0),
    ]
)

val_transform = Compose(
    [
        LoadImaged(keys=["image", "label"]),
        EnsureChannelFirstd(keys="image"),
        SingleModality(keys="image"),
        EnsureTyped(keys=["image", "label"]),
        ConvertToMultiChannelBasedOnBratsClasses(keys="label"),
        Orientationd(keys=["image", "label"], axcodes="RAS"),
        Spacingd(
            keys=["image", "label"],
            pixdim=(1.0, 1.0, 1.0),
            mode=("bilinear", "nearest"),
        ),
        # Add RandSpatialCropd for validation to ensure consistent input size
        RandSpatialCropd(keys=["image", "label"], roi_size=[224, 224, 144], random_size=False), # Reverted ROI size
        NormalizeIntensityd(keys="image", nonzero=True, channel_wise=True),
    ]
)

train_ds = DecathlonDataset(
    root_dir=root_dir,
    task="Task01_BrainTumour",
    transform=train_transform,
    section="training",
    download=True,
    cache_rate=0.0,
    num_workers=0,
)
train_loader = DataLoader(train_ds, batch_size=1, shuffle=True, num_workers=0)
val_ds = DecathlonDataset(
    root_dir=root_dir,
    task="Task01_BrainTumour",
    transform=val_transform,
    section="validation",
    download=True,
    cache_rate=0.0,
    num_workers=0,
)
val_loader = DataLoader(val_ds, batch_size=1, shuffle=False, num_workers=0)

print(train_ds[0]['image'].size()) #if ([4, 224, 224, 144]) then you have 4 modalities

import torch.optim as optim

os.environ['PYTORCH_ALLOC_CONF'] = 'expandable_segments:True'

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Ensure previous model and tensors are explicitly deleted to free GPU memory
if 'model' in locals() and model is not None:
    del model
torch.cuda.empty_cache()

model = UNet3D(1, 3).to(device)
batch_data = train_ds[0]
scaler = torch.cuda.amp.GradScaler()  # Re-enabled for mixed precision
# enable cuDNN benchmark
torch.backends.cudnn.benchmark = True
inputs, labels = (
            batch_data["image"].to(device),
            batch_data["label"].to(device),
        )
# Removed hardcoded reshape; model expects inputs for each modality to be 1 channel, handled internally
# The U_Transformer's forward method expects an input of shape (batch, modalities, H, W, D)
# Then it internally reshapes for each encoder.
# The DataLoader already provides batches with the correct shapes after transformations.
# For batch_size=1, inputs will be (1, 4, 224, 224, 144) and labels will be (1, 3, 224, 224, 144).

#modalities = np.arange(4)

print(f"This is intial input size {inputs.size()}")
print(f"This is intial label size {labels.size()}")

# print('initial input size', inputs.size())
#selects first channel from modalities (for single channel use) -> now have [H,W,D]
input_slice = inputs[0, :, :, :]
print('input_slice size', input_slice.size())
print('label_slice size', label_slice.size())

# input = input_slice.resize(1, 1, 224, 224, 144)
# labels = labels.resize(1, 3, 224, 224, 144)
#labels = labels.resize(1, 3, 224, 224, 144)

#adds your channel
input = input_slice.unsqueeze(0) #-> should be [1,H,W,D]

#add your batch
input = input.unsqueeze(0) #-> should be [1,1,H,W,D]
labels = labels.unsqueeze(0)

print('FINAL input_slice size', input.size())
print('FINAL label_slice size', labels.size())


loss_function = DiceLoss(smooth_nr=0, smooth_dr=1e-5, squared_pred=True, to_onehot_y=False, sigmoid=True)
optimizer = torch.optim.Adam(model.parameters(), 1e-4, weight_decay=1e-5)
#lr_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max_epochs)

dice_metric = DiceMetric(include_background=True, reduction="mean")
dice_metric_batch = DiceMetric(include_background=True, reduction="mean_batch")


model.train()
epoch_loss = 0
step = 0
step_start = time.time()
with torch.profiler.profile(
            activities=[
                torch.profiler.ProfilerActivity.CPU,
                torch.profiler.ProfilerActivity.CUDA,
            ],
            #schedule=torch.profiler.schedule(wait=1, warmup=1, active=3),
            on_trace_ready=torch.profiler.tensorboard_trace_handler('./log/profile'),
            with_stack=True
        ) as prof:
  with torch.cuda.amp.autocast():  # Re-enabled AMP
      outputs = model(input)
      loss = loss_function(outputs, labels)

  scaler.scale(loss).backward()  # Re-enabled scaler
  scaler.step(optimizer)  # Re-enabled scaler
  scaler.update()  # Re-enabled scaler
  #loss.backward()
  #optimizer.step()

  epoch_loss += loss.item()
  print(
      f"{step}/{len(train_ds)}"
      f", train_loss: {loss.item():.4f}"
      f", step time: {(time.time() - step_start):.4f}"
  )
              #prof.step()

  #print('outputs', outputs.shape)

max_epochs = 300
val_interval = 1
VAL_AMP = True

device = torch.device("cuda:0")
model = UNet3D(1, 3).to(device)
loss_function = DiceLoss(smooth_nr=0, smooth_dr=1e-5, squared_pred=True, to_onehot_y=False, sigmoid=True)
optimizer = torch.optim.Adam(model.parameters(), 1e-4, weight_decay=1e-5)
lr_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max_epochs)

dice_metric = DiceMetric(include_background=True, reduction="mean")
dice_metric_batch = DiceMetric(include_background=True, reduction="mean_batch")

post_trans = Compose([Activations(sigmoid=True), AsDiscrete(threshold=0.5)])


# define inference method
def inference(input):
    def _compute(input):
        return sliding_window_inference(
            inputs=input,
            roi_size=(224, 224, 144), # Reverted to match original training crop size
            sw_batch_size=2,
            predictor=model,
            overlap=0.5,
        )

    if VAL_AMP:
        with torch.autocast("cuda"):
            return _compute(input)
    else:
        return _compute(input)


# use amp to accelerate training
scaler = torch.GradScaler("cuda")
# enable cuDNN benchmark
torch.backends.cudnn.benchmark = True

best_metric = -1
best_metric_epoch = -1
best_metrics_epochs_and_time = [[], [], []]
epoch_loss_values = []
metric_values = []
metric_values_tc = []
metric_values_wt = []
metric_values_et = []
#set-up model
device = torch.device("cuda:0")
#model = U_Transformer(1, 3).to(device)
torch.cuda.empty_cache()

# Re-initialize optimizer, loss function, metrics, and scaler after model setup
loss_function = DiceLoss(smooth_nr=0, smooth_dr=1e-5, squared_pred=True, to_onehot_y=False, sigmoid=True)
optimizer = torch.optim.Adam(model.parameters(), 1e-4, weight_decay=1e-5)
# lr_scheduler is also defined in 1SiHZ1k9PEwo, re-initialize for consistency if needed, but not directly causing this error.
lr_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max_epochs)
dice_metric = DiceMetric(include_background=True, reduction="mean")
dice_metric_batch = DiceMetric(include_background=True, reduction="mean_batch")
scaler = torch.GradScaler("cuda") # Re-initialize the scaler

total_start = time.time()
accum_iter = 10

#sanity checks
print(f"Image shape: {batch_data["image"].shape}") #-> should be ([1, 1, 244, 244, 144])
print(f"Label shape: {batch_data["label"].shape}") #-> should be ([1, 3, 244, 244, 144])

for epoch in range(max_epochs):
    epoch_start = time.time()
    print("-" * 10)
    print(f"epoch {epoch + 1}/{max_epochs}")
    model.train()
    epoch_loss = 0
    step = 0
    for batch_data in train_loader:
        step_start = time.time()

        inputs, labels = (
            batch_data["image"].to(device),
            batch_data["label"].to(device),
        )
        # #print('full inputs size', inputs.size())
        # input_slice = inputs[:, 0, :, :, :] # first modality
        # #print('input_slice size', input_slice.size())

        # input = input_slice.resize(1, 1, 224, 224, 144)
        # labels = labels.resize(1, 3, 224, 224, 144)

        """with torch.profiler.profile(
            activities=[
                torch.profiler.ProfilerActivity.CPU,
                torch.profiler.ProfilerActivity.CUDA,
            ],
            schedule=torch.profiler.schedule(wait=1, warmup=1, active=3),
            on_trace_ready=torch.profiler.tensorboard_trace_handler('./log/profile'),
            with_stack=True
        ) as prof:"""
        with torch.autocast("cuda"):

          outputs = model(inputs)

          #print(f"Outputs.shape:{outputs.shape}") # should be ([1,3,244,244,144])
          #print(f"labels.shape: {labels.shape}")  # should be ([1,3,244,244,144])

          loss = loss_function(outputs, labels) / accum_iter
        scaler.scale(loss).backward()

        if ((step + 1) % accum_iter == 0) or (step + 1 == len(train_loader)):
          scaler.step(optimizer)
          scaler.update()
          optimizer.zero_grad()
          epoch_loss += loss.item() * accum_iter

          print(
              f"{step}/{len(train_ds) // train_loader.batch_size}"
              f", train_loss: {(loss.item() * accum_iter):.4f}"
              f", step time: {(time.time() - step_start):.4f}"
          )

        step += 1
            #prof.step()

    lr_scheduler.step()
    epoch_loss /= step
    epoch_loss_values.append(epoch_loss)
    print(f"epoch {epoch + 1} average loss: {epoch_loss:.4f}")

    if (epoch + 1) % val_interval == 0:
        model.eval()
        with torch.no_grad():
            for val_data in val_loader:
                val_inputs, val_labels = (
                    val_data["image"].to(device),
                    val_data["label"].to(device),
                )
                #print('full inputs size', inputs.size())
                #val_input_slice = val_inputs[:, 0, :, :, :] # first modality
                #print('input_slice size', input_slice.size())

                # val_input = val_input_slice.resize(1, 1, 224, 224, 144)
                # val_labels = val_labels.resize(1, 3, 224, 224, 144)

                val_outputs = inference(val_inputs)
                #val_output = decollate_batch(val_outputs)
                #val_outputs = post_trans(val_output)
                val_outputs = post_trans(val_outputs)
                # print(f"val_outputs: {val_outputs.unique()}")
                # print(f"val_labels:  {val_labels.unique()}")
                dice_metric(y_pred=val_outputs, y=val_labels)
                dice_metric_batch(y_pred=val_outputs, y=val_labels)

            metric = dice_metric.aggregate().item()
            metric_values.append(metric)
            metric_batch = dice_metric_batch.aggregate()
            metric_tc = metric_batch[0].item()
            metric_values_tc.append(metric_tc)
            metric_wt = metric_batch[1].item()
            metric_values_wt.append(metric_wt)
            metric_et = metric_batch[2].item()
            metric_values_et.append(metric_et)
            dice_metric.reset()
            dice_metric_batch.reset()

            if metric > best_metric:
                best_metric = metric
                best_metric_epoch = epoch + 1
                best_metrics_epochs_and_time[0].append(best_metric)
                best_metrics_epochs_and_time[1].append(best_metric_epoch)
                best_metrics_epochs_and_time[2].append(time.time() - total_start)
                torch.save(
                    model.state_dict(),
                    os.path.join(root_dir, "best_metric_model.pth"),
                )
                print("saved new best metric model")
            print(
                f"current epoch: {epoch + 1} current mean dice: {metric:.4f}"
                f" tc: {metric_tc:.4f} wt: {metric_wt:.4f} et: {metric_et:.4f}"
                f"\nbest mean dice: {best_metric:.4f}"
                f" at epoch: {best_metric_epoch}"
            )
    print(f"time consuming of epoch {epoch + 1} is: {(time.time() - epoch_start):.4f}")
total_time = time.time() - total_start